CREATE TABLE CLIENTE(
    COD_CLIENTE INT PRIMARY KEY NOT NULL,
    NOME_CLIENTE VARCHAR(10) NOT NULL,
    ENDERECO_CLIENTE VARCHAR(100) NOT NULL,
    BAIRRO_CLIENTE VARCHAR(100) NOT NULL
);

CREATE TABLE TELEFONE_CLIENTE(
    COD_TELEFONE INT PRIMARY KEY NOT NULL,
    NUMERO_TELEFONE VARCHAR(20) NOT NULL,
    COD_CLIENTE INT,
    FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
);